o --> snfsing,svsing.
o --> snmsing,svsing.
o --> snfpl,svpl.
o --> snmpl,svpl.
snfsing  --> detfsing,nfsing.  
snmsing --> detmsing,nmsing.
snfpl  --> detfpl,nfpl.  
snmpl --> detmpl,nmpl.
snf --> npropf.
snm --> npropm.
svsing  -->  prosing,vsing,sprepsing.
svsing  -->  propl,vsing,spreppl.
svpl  -->  prosing,vpl,sprepsing.
svpl  -->  propl,vpl,spreppl.
svsing  -->  vsing.
svpl  -->  vpl.
sprepsing -->  prep,snfsing.
sprepsing -->  prep,snmsing.
spreppl -->  prep,snfpl.
spreppl -->  prep,snfpl.
   
detfsing  -->  [la].
detfpl  -->  [las].
detmsing --> [el].
detmpl --> [los].
detfsing  -->  [una].
detfpl  -->  [unas].
detmsing  -->  [un].
detmpl  -->  [unos].
nfsing  -->  [mujer].
nfpl  -->  [mujeres].
nmsing  -->  [hombre].
nmpl  -->  [hombres].
nmsing -->  [perro].
nmpl -->  [perros].
nfsing -->  [gata].
nfpl -->  [gatas].
nmsing -->  [gato].
nmpl -->  [gatos].
nmsing -->  [ladron].
nmpl -->  [ladrones].
npropf -->  [maria].
npropm -->  [pedro].
prosing  --> [le].
propl  --> [les].
vsing  -->  [disparo].
vpl  -->  [dispararon].
prep  --> [a].
